language: generic

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend mengxiaozhao/udagram-frontend:latest
  - docker build -t udagram--api-user ./udagram-user
  - docker tag udagram--api-user mengxiaozhao/udagram-api-user:latest
  - docker build -t udagram-api-feed ./udagram-feed
  - docker tag udagram-api-feed mengxiaozhao/udagram-api-feed:latest
  - docker build -t reverseproxy ./reverse-proxy
  - docker tag reverseproxy mengxiaozhao/reverseproxy:latest

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mengxiaozhao/udagram-frontend
  - docker push mengxiaozhao/udagram-api-user
  - docker push mengxiaozhao/udagram-api-feed
  - docker push mengxiaozhao/reverseproxy
